////

 Copyright (c) Microsoft
 Copyright (c) 2024-present Eclipse ThreadX contributors
 
 This program and the accompanying materials are made available 
 under the terms of the MIT license which is available at
 https://opensource.org/license/mit.
 
 SPDX-License-Identifier: MIT
 
 Contributors: 
     * Frédéric Desbiens - Initial AsciiDoc version.

////

= About this guide
:description: This guide contains comprehensive information about TraceX, the Windows-based system analysis tool from Eclipse Foundation.

This guide contains comprehensive information about TraceX, the Microsoft Windows-based system analysis tool for Eclipse ThreadX.

It is intended for the embedded real-time software developer using ThreadX Real-Time Operating System (RTOS) and add-on components. The developer should be familiar with standard ThreadX, FileX, and NetX Duo concepts.

== Organization

* xref:chapter1.adoc[Chapter 1] - contains an basic overview of TraceX and describes its relationship to real-time development.
* xref:chapter2.adoc[Chapter 2] - gives the basic steps to install and use TraceX to analyze your application right out of the box.
* xref:chapter3.adoc[Chapter 3] - describes the main features of TraceX.
* xref:chapter4.adoc[Chapter 4] - details performance analysis features of TraceX.
* xref:chapter5.adoc[Chapter 5] - describes how to set up ThreadX, FileX, and NetX Duo in order to generate a trace buffer that is viewable by TraceX.
* xref:chapter6.adoc[Chapter 6] - describes TraceX events in detail.
* xref:chapter7.adoc[Chapter 7] - describes FileX events in detail.
* xref:chapter8.adoc[Chapter 8] - describes NetX Duo events in detail.
* xref:chapter9.adoc[Chapter 9] - describes USBX events in detail.
* xref:chapter10.adoc[Chapter 10] - describes creating custom user events in detail.
* xref:chapter11.adoc[Chapter 11] - describes the internal trace buffer in detail.
* xref:appendix-a.adoc[Appendix A] - ThreadX port-specific file with its time-stamp source for gathering trace events.
* xref:appendix-b.adoc[Appendix B] - ThreadX _tx_trace.h_ file that shows implementation details regarding the event trace buffer.
* xref:appendix-c.adoc[Appendix C] - Summarizes command line utilities for converting various file formats into proper TraceX binary files.
* xref:appendix-d.adoc[Appendix D] - Examples of dumping trace files from various development tools.

== Guide Conventions

_Italics_ - Typeface denotes book titles, emphasizes important words, and indicates variables.

*Boldface* - Typeface denotes file names, key words, and further emphasizes important words and variables.

NOTE: Indicates information of note.

== Troubleshooting

For troubleshooting, be sure to collect the following information:

. A detailed description of the problem, including frequency of occurrence and whether it can be reliably reproduced.
. A detailed description of any changes to the application and/or ThreadX that preceded the problem.
. The contents of the __tx_version_id_ string found in the _tx_port.h_ file of your distribution. This string provides valuable information regarding your run-time environment.
. The contents in RAM of the __tx_build_options_ ULONG variable. This variable gives information on how your ThreadX library was built.
