#!/usr/bin/env python3
"""Fetch published GitHub security advisories for Eclipse ThreadX components
and render them as AsciiDoc pages under each component's Antora module.

Authentication: uses `gh auth token` from the GitHub CLI. Falls back to the
GH_TOKEN or GITHUB_TOKEN environment variables if `gh` is not available.

Usage:
    python scripts/fetch-security-advisories.py
    python scripts/fetch-security-advisories.py --component threadx
    python scripts/fetch-security-advisories.py --dry-run
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _advisory_common import (  # noqa: E402
    COMPONENTS, DISPLAY_NAME, fetch_advisories, resolve_token,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_ROOT = REPO_ROOT / "rtos-docs"

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "moderate": 2, "low": 3, "none": 4}


# --------------------------------------------------------------------------- #
# Markdown -> AsciiDoc (light conversion for advisory descriptions)
# --------------------------------------------------------------------------- #

def md_to_adoc(text: str, base_level: int = 2) -> str:
    """Convert GitHub-flavored markdown to AsciiDoc.

    ``base_level`` is the AsciiDoc section level that the shallowest markdown
    heading should map to. The advisory page title is level 0 and the
    enclosing section (``== Description``) is level 1, so descriptions
    normalize to level 2 (``===``) and deeper.
    """
    if not text:
        return ""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    raw_lines = text.split("\n")

    # Determine the minimum heading depth used in the description (outside
    # fenced code blocks) so we can normalize section levels.
    min_depth: int | None = None
    in_fence = False
    for line in raw_lines:
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = re.match(r"^(#{1,6})\s+\S", line)
        if m:
            depth = len(m.group(1))
            if min_depth is None or depth < min_depth:
                min_depth = depth
    shift = (base_level - min_depth) if min_depth is not None else 0

    out_lines: list[str] = []
    in_fence = False
    for line in raw_lines:
        if line.startswith("```"):
            out_lines.append("----")
            in_fence = not in_fence
            continue
        if in_fence:
            out_lines.append(line)
            continue
        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m:
            level = max(1, min(5, len(m.group(1)) + shift))
            out_lines.append("=" * (level + 1) + " " + m.group(2))
            continue
        # Horizontal rule: `---` / `***` / `___` (3+). Render as an AsciiDoc
        # thematic break instead of letting Asciidoctor treat `----`/`****`
        # as an unterminated delimited block.
        if re.match(r"^\s*(-{3,}|\*{3,}|_{3,})\s*$", line):
            out_lines.append("'''")
            continue
        # Escape leading `N. ` so Asciidoctor doesn't start an ordered list
        # mid-paragraph (e.g. text describing step 2 after a gap).
        m = re.match(r"^(\s*)(\d+)\.\s", line)
        if m:
            line = f"{m.group(1)}{m.group(2)}\\. " + line[m.end():]
        out_lines.append(line)

    # Close any dangling fenced block so Asciidoctor doesn't complain about an
    # unterminated listing block.
    if in_fence:
        out_lines.append("----")

    converted = "\n".join(out_lines)
    # [text](url) -> url[text]
    converted = re.sub(r"\[([^\]]+)\]\((https?://[^)\s]+)\)", r"\2[\1]", converted)
    # Bare <url> -> url
    converted = re.sub(r"<(https?://[^>]+)>", r"\1", converted)
    return converted.strip()


# --------------------------------------------------------------------------- #
# AsciiDoc rendering
# --------------------------------------------------------------------------- #

@dataclass
class AdvisorySummary:
    ghsa_id: str
    cve_id: str
    severity: str
    summary: str
    published: str  # ISO date (YYYY-MM-DD)
    filename: str


FILE_HEADER = """////
Generated by scripts/fetch-security-advisories.py — do not edit by hand.
////
"""


def adoc_escape_cell(s: str) -> str:
    """Escape a string for use inside an AsciiDoc table cell (| delimited)."""
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


def nowrap_id(s: str) -> str:
    """Keep identifiers like GHSA-… and CVE-… on a single line.

    Browsers break lines at regular hyphens; swapping them for U+2011
    (non-breaking hyphen) prevents the GHSA / CVE columns from wrapping
    without requiring any theme-level CSS changes.
    """
    return (s or "").replace("-", "\u2011")


def render_advisory(advisory: dict) -> tuple[str, AdvisorySummary]:
    ghsa = advisory.get("ghsa_id", "UNKNOWN")
    cve = advisory.get("cve_id") or "—"
    severity = (advisory.get("severity") or "unknown").lower()
    summary = advisory.get("summary", "").strip()
    description = advisory.get("description", "") or ""
    html_url = advisory.get("html_url", "")
    published_at = advisory.get("published_at", "") or ""
    updated_at = advisory.get("updated_at", "") or ""
    cvss = advisory.get("cvss") or {}
    cvss_score = cvss.get("score")
    cvss_vector = cvss.get("vector_string") or ""
    cwes = advisory.get("cwes") or []
    vulns = advisory.get("vulnerabilities") or []
    references = advisory.get("references") or []

    published_date = published_at[:10] if published_at else ""

    lines: list[str] = [FILE_HEADER.rstrip(), ""]
    title = f"= {ghsa}"
    if summary:
        title += f": {summary}"
    lines += [title, ":page-role: security-advisory", ""]

    # Metadata block.
    lines += ["[cols=\"1h,3\"]", "|===", ""]
    ghsa_display = nowrap_id(ghsa)
    cve_display = nowrap_id(cve)
    lines += [
        f"| GHSA ID | {html_url}[{ghsa_display}]"
        if html_url else f"| GHSA ID | {ghsa_display}"
    ]
    lines += [f"| CVE ID | {cve_display}"]
    lines += [f"| Severity | {severity.capitalize()}"]
    if cvss_score is not None:
        vec = f" (`{cvss_vector}`)" if cvss_vector else ""
        lines += [f"| CVSS score | {cvss_score}{vec}"]
    if cwes:
        cwe_txt = ", ".join(
            f"https://cwe.mitre.org/data/definitions/{c['cwe_id'].split('-')[-1]}.html[{c['cwe_id']}]"
            if c.get("cwe_id", "").startswith("CWE-") else c.get("cwe_id", "")
            for c in cwes
        )
        lines += [f"| CWE | {cwe_txt}"]
    if published_date:
        lines += [f"| Published | {nowrap_id(published_date)}"]
    if updated_at:
        lines += [f"| Last updated | {nowrap_id(updated_at[:10])}"]
    lines += ["|===", ""]

    # Affected / patched versions.
    if vulns:
        lines += ["== Affected packages", ""]
        lines += ["[cols=\"2,3,3\", options=\"header\"]", "|==="]
        lines += ["| Package | Vulnerable versions | Patched versions"]
        for v in vulns:
            pkg = (v.get("package") or {}).get("name") or "—"
            vrange = v.get("vulnerable_version_range") or "—"
            patched = v.get("patched_versions") or "—"
            lines += [
                f"| {adoc_escape_cell(pkg)} "
                f"| {adoc_escape_cell(vrange)} "
                f"| {adoc_escape_cell(patched)}"
            ]
        lines += ["|===", ""]

    # Description.
    if description:
        lines += ["== Description", "", md_to_adoc(description), ""]

    # References.
    if references:
        lines += ["== References", ""]
        for ref in references:
            url = ref.get("url") if isinstance(ref, dict) else ref
            if url:
                lines += [f"* {url}[{url}]"]
        lines += [""]

    content = "\n".join(lines).rstrip() + "\n"

    return content, AdvisorySummary(
        ghsa_id=ghsa,
        cve_id=cve,
        severity=severity,
        summary=summary,
        published=published_date,
        filename=f"{ghsa.lower()}.adoc",
    )


def render_index(component: str, advisories: list[AdvisorySummary]) -> str:
    display = DISPLAY_NAME.get(component, component)
    lines: list[str] = [FILE_HEADER.rstrip(), ""]
    lines += [f"= {display} security advisories", ""]

    if not advisories:
        lines += [
            f"No published security advisories are currently available for {display}.",
            "",
            "See the "
            f"https://github.com/{COMPONENTS[component]}/security/advisories[{display} advisories on GitHub] "
            "for the latest status.",
            "",
        ]
        return "\n".join(lines).rstrip() + "\n"

    lines += [
        f"The table below lists published security advisories for {display}, "
        "newest first. Click a GHSA ID for full details.",
        "",
        "[cols=\"1,1,1,3,1\", options=\"header\", role=\"datatable\"]",
        "|===",
        "| Published | GHSA ID | CVE ID | Summary | Severity",
    ]
    for adv in advisories:
        # Antora resolves xrefs relative to the module's `pages/` root, so
        # same-module links from `pages/security/index.adoc` must include the
        # `security/` prefix.
        link = f"xref:security/{adv.filename}[{nowrap_id(adv.ghsa_id)}]"
        lines += [
            f"| {adoc_escape_cell(nowrap_id(adv.published))} "
            f"| {link} "
            f"| {adoc_escape_cell(nowrap_id(adv.cve_id))} "
            f"| {adoc_escape_cell(adv.summary)} "
            f"| {adv.severity.capitalize()}"
        ]
    lines += ["|===", ""]
    return "\n".join(lines).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# File I/O
# --------------------------------------------------------------------------- #

def write_text(path: Path, content: str, dry_run: bool) -> None:
    if dry_run:
        print(f"  [dry-run] would write {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" keeps generated AsciiDoc LF-only on Windows too.
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def clean_stale_files(security_dir: Path, keep: Iterable[str], dry_run: bool) -> None:
    """Remove generated GHSA files that are no longer in the fetched set."""
    if not security_dir.is_dir():
        return
    keep_set = set(keep) | {"index.adoc"}
    for existing in security_dir.glob("ghsa-*.adoc"):
        if existing.name not in keep_set:
            if dry_run:
                print(f"  [dry-run] would remove stale {existing}")
            else:
                existing.unlink()


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def process_component(component: str, token: str, dry_run: bool) -> int:
    owner_repo = COMPONENTS[component]
    display = DISPLAY_NAME[component]
    security_dir = DOCS_ROOT / component / "modules" / "ROOT" / "pages" / "security"

    if not (DOCS_ROOT / component).is_dir():
        print(f"  skip: {DOCS_ROOT / component} does not exist", file=sys.stderr)
        return 0

    print(f"[{display}] fetching advisories from {owner_repo} ...")
    raw = fetch_advisories(owner_repo, token)
    print(f"  got {len(raw)} advisory record(s)")

    summaries: list[AdvisorySummary] = []
    for advisory in raw:
        content, summary = render_advisory(advisory)
        summaries.append(summary)
        write_text(security_dir / summary.filename, content, dry_run)

    # Sort newest first; items with no date go last.
    summaries.sort(
        key=lambda a: (a.published or "0000-00-00", a.ghsa_id),
        reverse=True,
    )

    index_content = render_index(component, summaries)
    write_text(security_dir / "index.adoc", index_content, dry_run)

    clean_stale_files(security_dir, [a.filename for a in summaries], dry_run)
    return len(summaries)


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    p.add_argument(
        "--component", action="append", choices=sorted(COMPONENTS),
        help="Restrict to one or more components (default: all).",
    )
    p.add_argument("--dry-run", action="store_true", help="Do not write files.")
    return p.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    token = resolve_token()
    components = args.component or list(COMPONENTS)

    total = 0
    for component in components:
        total += process_component(component, token, args.dry_run)

    mode = " (dry-run)" if args.dry_run else ""
    print(f"\nDone{mode}: rendered {total} advisory page(s) across {len(components)} component(s).")
    if not args.dry_run:
        print("Reminder: add a nav entry to each component's nav.adoc pointing at "
              "`security/index.adoc` if you haven't already.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
